# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orchestrate or schedule a set of jobs
workflows:
  version: 2
  default:
    jobs:
     - prepare

jobs:
  prepare:
    docker:
     - image: alpine/git:latest
  steps:
   - checkout
   - persist_to_workspace:
      root: .
      paths: .